version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
  after_build:
  - 7z a Handout_test.zip "%APPVEYOR_BUILD_FOLDER%\Fisica\Physics2_class2 - handout\Game\solution.exe"
  - 7z a Handout_test.zip "%APPVEYOR_BUILD_FOLDER%\Fisica\README.md"

  - path: Handout_test.zip
